name: tic_tac_app
description: A new Flutter project.

version: 1.0.5+3

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^1.0.3
  lottie: ^1.2.2
  flutter_bloc: ^8.0.1
  simple_animations: ^4.0.1
  equatable: ^2.0.3
  font_awesome_flutter: ^10.1.0
  json_annotation: ^4.4.0
  build_runner: ^2.1.8
  animated_text_kit: ^4.2.1
  loading_indicator: ^3.0.3
  intl: ^0.17.0
  socket_io_client: ^1.0.2
  get: ^4.6.1
  shared_preferences: ^2.0.13
  http: ^0.13.4
  package_info: ^2.0.2
  permission_handler: ^9.2.0
  flutter_downloader: ^1.7.3
  open_file: ^3.2.1
  url_launcher: ^6.1.0
  path_provider: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  json_serializable: ^6.1.5

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/svg/
    - assets/lottie/

  fonts:
    - family: HelveticaNeueCyr
      fonts:
        - asset: fonts/HelveticaNeueCyr-Roman.ttf
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf